=== spot-next/core-next/docs/schemas/v1/itemtypes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="types">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="atomic" type="AtomicType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="collection" type="CollectionType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="map" type="MapType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="enum" type="EnumType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="bean" type="BeanType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="type" type="ItemType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="relation" type="RelationType"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="BaseType" abstract="true">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="JavaType" abstract="true">
		<xs:complexContent>
			<xs:extension base="BaseComplexType">
				<xs:sequence>
					<xs:element name="properties" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>
								Defines the list of item properties.
							</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:sequence>
								<xs:element name="property" type="Property"
									minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="extends" type="xs:string">
					<xs:annotation>
						<xs:documentation>
							Defines the super class of the given type.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="abstract" type="xs:boolean">
					<xs:annotation>
						<xs:documentation>
							Defines if the type is abstract.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="BaseComplexType" abstract="true">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:sequence>
					<xs:element name="interfaces" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>
								Specifies the interfaces the type implements.
								Only interfaces with default methods or no method at all are
								supported. All other interfaces will lead to build errors!
							</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:sequence>
								<xs:element name="interface" type="Interface"
									minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="package" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>
							Defines the java package of the item type.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CollectionType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="elementType" type="xs:string" use="required" />
				<xs:attribute name="collectionType" type="CollectionsType"
					default="List" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MapType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="keyType" type="xs:string" use="required" />
				<xs:attribute name="valueType" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AtomicType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="className" type="xs:string" use="required" />
				<xs:attribute name="array" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EnumType">
		<xs:complexContent>
			<xs:extension base="BaseComplexType">
				<xs:sequence>
					<xs:element name="value" type="EnumValue" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EnumValue">
		<xs:attribute name="code" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="BeanType">
		<xs:complexContent>
			<xs:extension base="JavaType">
				<xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ItemType">
		<xs:complexContent>
			<xs:extension base="JavaType">
				<xs:attribute name="typeCode" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>
							The internal code of the item type, used for
							storage and other internal functionality.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="persistable" type="xs:boolean"
					default="true">
					<xs:annotation>
						<xs:documentation>
							Determines if this item type can be stored by
							the underlying persistence framework.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DefaultValue" mixed="true">
		<xs:attribute name="value" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Persistence" mixed="true">
		<xs:attribute name="columnType" use="required" type="DatabaseColumnType" />
	</xs:complexType>

	<xs:complexType name="Property">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="modifiers" type="Modifiers" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="accessors" type="Accessors" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="validators" type="Validators" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="defaultValue" type="DefaultValue"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="persistence" type="Persistence"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the type of the property
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="localized" type="xs:boolean"
			default="false">
			<xs:annotation>
				<xs:documentation>
					Specifies if additional localized getters and
					setters should be created. This is only valid for types that
					implement the interface 'io.spotnext.core.types.Localizable'
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Validators">
		<xs:sequence>
			<xs:element name="validator" type="Validator" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Validator">
		<xs:sequence>
			<xs:element name="argument" type="ValidatorArgument"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="javaClass" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="ValidatorArgument">
		<xs:attribute name="name" use="required" />
		<xs:attribute name="numberValue" use="optional" />
		<xs:attribute name="stringValue" use="optional" />
	</xs:complexType>

	<xs:complexType name="Interfaces">
		<xs:sequence>
			<xs:element name="interface" type="Interface" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Interface">
		<xs:sequence>
			<xs:element name="genericType" type="Argument" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="javaClass" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Argument">
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Modifiers">
		<xs:attribute name="unique" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>Defines if the property is part of the uniqueness
					criteria of the given type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="readable" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is readable.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="writable" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is writable.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="initial" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>
					Defines if the property can only be written once
					on item creation.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Accessors">
		<xs:attribute name="valueProvider" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					Defines the spring bean id that handles read and
					write access to the property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<!-- <xs:attribute name="getter" type="xs:boolean" default="true"> -->
		<!-- <xs:annotation> -->
		<!-- <xs:documentation> -->
		<!-- Defines if a getter method should be generated for -->
		<!-- the given property. -->
		<!-- </xs:documentation> -->
		<!-- </xs:annotation> -->
		<!-- </xs:attribute> -->
		<!-- <xs:attribute name="setter" type="xs:boolean" default="true"> -->
		<!-- <xs:annotation> -->
		<!-- <xs:documentation> -->
		<!-- Defines if a setter method should be generated for -->
		<!-- the given property. -->
		<!-- </xs:documentation> -->
		<!-- </xs:annotation> -->
		<!-- </xs:attribute> -->
	</xs:complexType>

	<xs:complexType name="RelationType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:sequence>
					<xs:element name="source" type="RelationNode" minOccurs="1"
						maxOccurs="1" />
					<xs:element name="target" type="RelationNode" minOccurs="1"
						maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="RelationNode">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="modifiers" type="Modifiers" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="validators" type="Validators" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="itemType" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Defines the itemtype of the relation endpoint.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mappedBy" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the property that references
					this endpoint item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="cardinality" type="RelationshipCardinality"
			use="required">
			<xs:annotation>
				<xs:documentation>
					Defines if the cardinality of the relation
					endpoint.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="collectionType" type="CollectionsType"
			default="Set">
			<xs:annotation>
				<xs:documentation>
					Defines the collection type of the property
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:simpleType name="RelationshipCardinality">
		<xs:restriction base="xs:string">
			<xs:enumeration value="one" />
			<xs:enumeration value="many" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="RelationshipType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OneToMany" />
			<xs:enumeration value="OneToOne" />
			<xs:enumeration value="ManyToMany" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="CollectionsType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="List" />
			<xs:enumeration value="Set" />
			<xs:enumeration value="Collection" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="DatabaseColumnType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DEFAULT">
				<xs:annotation>
					<xs:documentation>Empty placeholder, type will be automatically
						detected.
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CHAR">
				<xs:annotation>
					<xs:documentation>Single char</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="VARCHAR">
				<xs:annotation>
					<xs:documentation>Short string</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="LONGVARCHAR">
				<xs:annotation>
					<xs:documentation>Long string or text</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="BLOB">
				<xs:annotation>
					<xs:documentation>Large binary object</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CLOB">
				<xs:annotation>
					<xs:documentation>Large character object</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TIME">
				<xs:annotation>
					<xs:documentation>Time</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TIMESTAMP">
				<xs:annotation>
					<xs:documentation>Timestamp</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DATE">
				<xs:annotation>
					<xs:documentation>Date</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="VARBINARY">
				<xs:annotation>
					<xs:documentation>Byte array</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="BIT">
				<xs:annotation>
					<xs:documentation>0 or 1, like a boolean</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DOUBLE">
				<xs:annotation>
					<xs:documentation>Double</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="FLOAT">
				<xs:annotation>
					<xs:documentation>Float</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TINYINT">
				<xs:annotation>
					<xs:documentation>Byte</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SMALLINT">
				<xs:annotation>
					<xs:documentation>Short</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="INTEGER">
				<xs:annotation>
					<xs:documentation>Integer</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="BIGINT">
				<xs:annotation>
					<xs:documentation>BigInteger</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NUMERIC">
				<xs:annotation>
					<xs:documentation>BigDecimal</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== spot-next/core-next/spot-commerce-base/src/main/resources/commerce-base-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://spot-next.io/schemas/v1/itemtypes.xsd">

	<!-- enums -->

	<enum name="OrderStatus" package="io.spotnext.itemtype.commerce.enumeration">
		<description>The render engine used to render cms items.</description>
		<value code="OPEN" />
		<value code="APPROVAL_PENDING" />
		<value code="APPROVED" />
		<value code="APPROVAL_REJECTED" />
		<value code="CANCELLED" />
		<value code="UNKNOWN" />
	</enum>

	<!-- base configuration -->

	<type name="BaseStore" typeCode="BaseStore" package="io.spotnext.itemtype.commerce.store"
		extends="UniqueIdItem">
		<description>This holds the base configuration for a store.</description>
		<properties>
			<property name="name" type="String">
				<description>The name of the base store.</description>
			</property>
			<property name="urlMatchers" type="StringList">
				<description>These regex strings are used to match browser url to the base store.</description>
			</property>
			<property name="countries" type="CountryList">
				<description>The countries that are assigned to this base store.</description>
			</property>
		</properties>
	</type>

	<!-- product related types -->

	<type name="Product" typeCode="Product" package="io.spotnext.itemtype.commerce.catalog"
		extends="UniqueIdItem">
		<description>The base type Product is used for all purchasable items.</description>
		<properties>
			<property name="name" type="String">
				<description>The name of the product.</description>
			</property>
			<property name="description"
				type="LocalizedString">
				<description>The localized description of the product.</description>
			</property>
			<property name="ean" type="String">
				<description>The EAN product code.</description>
			</property>
		</properties>
	</type>

	<type name="Category" typeCode="Category" package="io.spotnext.itemtype.commerce.catalog"
		extends="UniqueIdItem">
		<description>Categories are used to group products.</description>
		<properties>
			<property name="name" type="String">
			</property>
			<property name="description" type="LocalizedString">
			</property>
		</properties>
	</type>

	<type name="PriceGroup" typeCode="PriceGroup"
		package="io.spotnext.itemtype.commerce.catalog" extends="UniqueIdItem">
		<description>This is the container for all categories and products.</description>
		<properties>
		</properties>
	</type>

	<type name="Price" typeCode="Price" package="io.spotnext.itemtype.commerce.catalog">
		<description>This is the container for all categories and products.</description>
		<properties>
			<property name="productId" type="String">
				<description>The product id the price is used for.</description>
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
			<property name="userGroup" type="UserGroup">
				<description>The assigned user group.</description>
			</property>
			<property name="user" type="User">
				<description>The assigned user.</description>
			</property>
			<property name="price" type="BigDecimal">
				<description>The price value.</description>
			</property>
			<property name="currency" type="Currency">
				<description>The currency of the price.</description>
			</property>
			<property name="net" type="Boolean">
				<description>Defines if the price is net or gross.</description>
				<defaultValue>true</defaultValue>
			</property>
		</properties>
	</type>

	<type name="Tax" package="io.spotnext.itemtype.commerce.store"
		extends="UniqueIdItem">
		<properties>
			<property name="value" type="BigDecimal">
			</property>
			<property name="description" type="LocalizedString">
			</property>
			<property name="country" type="Country">
			</property>
		</properties>
	</type>

	<type name="Stock" package="io.spotnext.itemtype.commerce.store">
		<properties>
			<property name="productId" type="String">
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
			<property name="value" type="Integer">
				<description>The actual stock level.</description>
				<defaultValue>0</defaultValue>
			</property>
			<property name="reserved" type="Integer">
				<description>The reserved amount of stock.</description>
				<defaultValue>0</defaultValue>
			</property>
		</properties>
	</type>

	<type name="FutureStock" extends="Stock" package="io.spotnext.itemtype.commerce.store">
		<properties>
			<property name="availableAt" type="String">
				<description>Defines a future stock and when it will be available.</description>
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</type>

	<!-- cart and orders -->

	<type name="AbstractOrder" abstract="true"
		package="io.spotnext.itemtype.commerce.order" extends="UniqueIdItem">
		<description>The abstract base type for orders and carts.</description>
		<properties>
			<property name="customer" type="Customer">
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</type>

	<type name="AbstractOrderEntry" abstract="true"
		package="io.spotnext.itemtype.commerce.order">
		<properties>
			<property name="product" type="Product">
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</type>

	<type name="OrderEntry" extends="AbstractOrderEntry" package="io.spotnext.itemtype.commerce.order">

	</type>

	<type name="CartEntry" extends="AbstractOrderEntry" package="io.spotnext.itemtype.commerce.order">

	</type>

	<type name="Order" extends="AbstractOrder" package="io.spotnext.itemtype.commerce.order">
	</type>

	<type name="Cart" extends="AbstractOrder" package="io.spotnext.itemtype.commerce.order">
	</type>

	<!-- customers -->

	<type name="Customer" extends="User" package="io.spotnext.itemtype.commerce.customer">
		<properties>
			<property name="firstName" type="String">
			</property>
			<property name="lastName" type="String">
			</property>
			<property name="birthDay" type="Date">
			</property>
		</properties>
	</type>

	<relation name="Category2Product">
		<description>The categories the product is referenced by.</description>
		<source cardinality="many" itemType="Category" mappedBy="categories"></source>
		<target cardinality="many" itemType="Product" mappedBy="products">
			<description>The products in this catalog.</description>
		</target>
	</relation>
	
	<relation name="AbstractOrder2AbstractOrderEntry">
		<description>The categories the product is referenced by.</description>
		<source cardinality="one" itemType="AbstractOrder" mappedBy="order"></source>
		<target cardinality="many" itemType="AbstractOrderEntry" mappedBy="entries">
			<description>The order entries.</description>
		</target>
	</relation>
</types>

=== spot-next/core-next/spot-cms-base/src/main/resources/cms-base-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/mojo2012/spot/master/itemtypes/v1/itemtypes.xsd">

	<!-- enums -->

	<enum name="HtmlLinkTarget" package="at.spot.itemtype.cms.enumeration">
		<description>Represents an HTML link target used.</description>
		<value code="BLANK" />
		<value code="SELF" />
		<value code="PARENT" />
		<value code="TOP" />
	</enum>

	<enum name="Orientation" package="at.spot.itemtype.cms.enumeration">
		<description>Defines the orientation, eg. for layouts.</description>
		<value code="TOP" />
		<value code="BOTTOM" />
		<value code="LEFT" />
		<value code="RIGHT" />
	</enum>

	<enum name="TemplateRenderEngine" package="at.spot.itemtype.cms.enumeration">
		<description>The render engine used to render cms items.</description>
		<value code="VELOCITY" />
		<value code="FREEMARKER" />
		<value code="JSP" />
	</enum>

	<!-- image media -->
	<type name="ImageMedia" extends="FileMedia" package="at.spot.core.model.media">
		<properties>
		</properties>
	</type>

	<!-- cms item types -->

	<type name="AbstractCmsItem" abstract="true" package="at.spot.itemtype.cms.model"
		extends="UniqueIdItem">
		<properties>
			<property name="catalog" type="Catalog">
				<description>The content catalog of the item.</description>
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
			<property name="onlyOneRestrictionMustApply" type="Boolean">
				<description>
					f set to true, only one restriction must evaluate to "show cms item" 
					for the item to be visible.
				</description>
			</property>
		</properties>
	</type>

	<type name="CmsRestriction" extends="AbstractCmsItem" package="at.spot.itemtype.cms.model">
		<properties>
			<property name="evaluator" type="String">
				<description>The spring bean id of the corresponding evaluator implementation.</description>
			</property>
			<property name="evaluatorScript" type="String">
				<description>The beanshell script that evaluates the cms item visibility.</description>
			</property>
		</properties>
	</type>

	<type name="AbstractCmsComponent" abstract="true" extends="AbstractCmsItem"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="renderContextProvider" type="String">
				<description>
					The spring bean id of the context provider implementation.
				</description>
			</property>
			<property name="renderContextPreparationScript" type="String">
				<description>
				Beanshell code that is executed before the page rendering.
				It can be used to prepare the render context variables.
			</description>
			</property>
			<property name="content" type="String">
			</property>
			<property name="renderEngine" type="TemplateRenderEngine">
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</type>

	<type name="AbstractCmsContainerComponent" abstract="true"
		extends="AbstractCmsComponent" package="at.spot.itemtype.cms.model">
		<properties>
		</properties>
	</type>

	<type name="CmsComponent" extends="AbstractCmsComponent" package="at.spot.itemtype.cms.model">
		<properties>
		</properties>
	</type>

	<type name="ContentSlot" extends="AbstractCmsItem" package="at.spot.itemtype.cms.model">
		<properties>
		</properties>
	</type>

	<type name="MetaTag" extends="ConfigEntry" package="at.spot.itemtype.cms.model">
	</type>

	<type name="CmsPageTemplate" extends="AbstractCmsContainerComponent"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="title" type="LocalizedString">
			</property>
			<property name="favIconPath" type="LocalizedString">
			</property>
			<property name="favIcon" type="ImageMedia">
			</property>
			<property name="metaTags" type="StringList" />
		</properties>
	</type>

	<type name="CmsPage" extends="CmsPageTemplate" package="at.spot.itemtype.cms.model">
		<properties>
			<property name="urlMatches" type="StringList">
				<description>Holds the regex string to determine which URL should
						be handler by this page.</description>
			</property>
			<property name="template" type="CmsPageTemplate">
			</property>
		</properties>
	</type>

	<!-- special cms components -->

	<type name="AbstractNavigationEntry" abstract="true" extends="CmsComponent"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="name" type="String">
				<description>The navigation entry name.</description>
			</property>
		</properties>
	</type>

	<type name="NavigationLinkEntry" extends="AbstractNavigationEntry"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="href" type="String">
				<description>The href of the link.</description>
			</property>
			<property name="target" type="HtmlLinkTarget">
				<description>The HTML link target.</description>
			</property>
		</properties>
	</type>

	<type name="AbstractNavigationContainer" extends="AbstractCmsContainerComponent" abstract="true"
		package="at.spot.itemtype.cms.model">
		<properties>
		</properties>
	</type>

	<type name="NavigationBar" extends="AbstractNavigationContainer"
		package="at.spot.itemtype.cms.model" />

	<type name="Footer" extends="AbstractNavigationContainer" package="at.spot.itemtype.cms.model" />


	<relation name="AbstractCmsItem2CmsRestriction">
		<source itemType="AbstractCmsItem" cardinality="one" mappedBy="cmsItem" />
		<target itemType="CmsRestriction" cardinality="many" mappedBy="cmsRestrictions">
			<description>The restrictions evaluate if the current cms item should be rendered.</description>
		</target>
	</relation>

	<relation name="AbstractCmsContainerComponent2AbstractCmsComponent">
		<source itemType="AbstractCmsContainerComponent" cardinality="many"
			mappedBy="container" />
		<target itemType="AbstractCmsComponent" cardinality="many"
			mappedBy="components" />
	</relation>

	<relation name="ContentSlot2CmsComponent">
		<source itemType="ContentSlot" cardinality="many" mappedBy="contentSlot" />
		<target itemType="CmsComponent" cardinality="many" mappedBy="components" />
	</relation>

</types>
